### PR TITLE
adds check_estimator with workaround

### PR DESCRIPTION
**Pull request by solegalli**
Let me know what you think of this workaround.

(some of the code style changes were introduced automatically by black, I have nothing to do with it :p )

### CODE REVIEW

**Comment by solegalli** [comment]
hold on with merging until we hear from Chris. He said he might have time tonight to have a look.

**Comment by dodoarg** [comment]
I've spent some time looking into this issue and this is very close to what I came up with. I just didn't quite get to make it work because I was trying to not introduce additional files/classes and make it look less like a workaround. Not sure if that is possible though, well done.

Another approach I came across is to have an argument named with a preceding underscore _\_ignore\_format_ in the actual DatetimeFeatures() \_\_init\_\_, which conventionally means that it should be considered "private". To prevent that from being displayed in the docs we would then override the parameter list with a custom signature

**Comment by ChristopherGS** [comment]
This is a workable approach, but my recommendation would be to avoid unless absolutely necessary. Including attributes (hidden or not) into a class just for testing purposes reduces readability and increases complexity/ease of refactoring. Having to create test wrapper classes also introduces a larger surface area for bugs to occur.

Instead, why not just pick out the exact tests required? That decorator `parametrize_with_checks` is quite extreme. After reading the docs, I see sklearn offers the ability to cherry pick which tests you want to run via the `check_estimator(estimator, generate_only=True)` [flag](https://scikit-learn.org/stable/modules/generated/sklearn.utils.estimator_checks.check_estimator.html#sklearn-utils-estimator-checks-check-estimator)

So you could do something like:

```
from sklearn.utils.estimator_checks import check_estimator, _maybe_skip

def test_sklearn_compatible_datetime():
    subject = DatetimeFeatures()
    all_checks = check_estimator(subject, generate_only=True)
    _all_checks = list(all_checks)  # convert generator to list for ease of debugging
    for estimator, func in _all_checks:
        _maybe_skip(subject, func)  # tweak this and pick which tests you want to run
```

**Comment by solegalli** [comment]
> ther approach I came across is to have an argument named with a preceding underscore __ignore_format_ in the actual DatetimeFeatures() __init__, which conventionally means that it should be considered "private". To prevent that from being displayed in the docs we would then override the parameter list with a custom signat

Did you implement this already? could I see the code? @dodoarg

**Comment by solegalli** [comment]
> 

If we run the tests on the class as it is, without the ignore_flag, 13 tests pass, 15 fail. The ones that fail are kind of important though, they test for example that fit takes y, that fit returns self, that the class is pickable, that we do not override init params, that it is compatible with the pipeline, and that it has some required attributes like n_features_in.

We know our class should pass all of those tests, because we designed it correctly. But looking forward, if we make a change at a later stage and we do not have the tests... we could be introducing some sklearn convention violations.

**Comment by dodoarg** [comment]
I tried to implement that but although it seems quite straightforward I haven't found a single way to actually override any signature in the docs. What I mean is I'm quite sure what I'm doing _should_ override them, like having 
`.. autoclass: MyClass(my, new, signature)`
 in the correspondent .rst file or the first docstring line written as a signature 
```
def class MyClass():
"""MyClass(arg1=my, arg2=signature)
more docs
""" 
```
Whatever I do, the signature in the built html file seems unreachable and the only way I can see it change is by changing the __init__ params. My conclusion is that something else I haven't spotted is overriding my signature changes at some later stage of the building process which effectively puts it back to default. So, sorry, I don't really know how to do that


when you do this for example """MyClass(arg1=my, arg2=signature) etc etc""" sphinx will recognize that the first docstring line looks like a signature and will not display it in the text body in the built docs. However, the actual signature above that won't change and I really don't get why. See [autodoc_docstring_signature](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_docstring_signature)

**Comment by solegalli** [comment]
Yes, sphinx and its extensions are evil! I struggle all the time :_(

**Comment by solegalli** [comment]
I chatted with @ChristopherGS . He says that if he were us, he would re-write the tests so that the numpy arrays take datetime variables, and not change the class DatetimeFeatures to accommodate the tests. Because if we do that, then our tests are dictating our code, instead of the other way around. 

I see this point and I agree. This is not the first workaround I introduce to pass the tests. More like the second.

But, I am not motivated to re-write the tests for 2 reasons:
1- there are a lot of tests
2- every time sklearn changes their logic, they change their tests accordingly. If we have our own tests, we have more dependencies to adjust every time sklearn changes something. We don't have the capacity to maintain that.

So, my suggestion is as follows:
1- we merge the PR in the main repo without these changes, that would mean that we do not test the class with the check_estimator
2- I make a PR with these changes to main, to keep it open as an issue to resolve, this way we preserve these changes in case we want to use them at a later stage.

Would you agree with this @dodoarg ?

**Comment by dodoarg** [comment]
Yes I would be inclined to leave it as it is for now. As it stands we know that the class respects the sklearn standards we want it to comply with so that should be fine at least until some large change is introduced to the module/class

**Pull request closed without merging**
