### PR TITLE
[MRG] rewords user guide, adds more examples, adds missing param to docstrings

### PR DESCRIPTION
**Pull request by solegalli**
Hi @dodoarg 

Thank you so much for adding the examples. The user guide looks really good. A Masterpiece :)

I would say, this new class is ready to go.

Please do **NOT merge** yet, I want to first merge your notebook to the other repo, then link it to the user guide here, and then you can merge and we are done!

Unless you have anything else that was left to contribute to this PR?

### CODE REVIEW

**Comment by solegalli** [comment]
btw, I changed the .. code:: markdown to python because it was raising a warning in my environment. Not sure why. 

Also, I changed your beautiful tables to my horrible prints, because you need to have something else installed (tabulate?) which is not in the requirements file of the package. And I think I would prefer keeping the requirements to the minimum.

**Comment by dodoarg** [comment]
Thanks for the contributions here

About the prints, yes you do need tabulate installed to replicate those prints via pd.DataFrame.to_markdown but the docs were building properly even without that because I just copypasted it and to my surprise it looked like sphinx accepted the code markdown header (or decorator, or whatever it is called?)

I take it you want it to be reproducible exactly as is with the minimum requirements installed? Ok then

**Comment by dodoarg** [comment]
On what might be left:
atm I can think of two things mainly:

- your idea of adding a column containing the timezone offset values
- _week of the month_ is currently implemented in a rather unconventional way in that it counts sets of 7 days rather than looking at the actual calendar. This means that e.g. when day of the month = 6 week of the month is __always__ going to be 1 even if that particular month in the calendar started with say a saturday and so the 6th day would actually be in the 2nd week.
This was kind of a temporary workaround because there is no off the shelf pd function to extract wotm properly with a calendar-based approach. <br>
Should I investigate more and rework it, leave it as is or flat out remove it?

**Comment by solegalli** [comment]
I am inclined to say "remove" it. If it is not precise.... most users don't look at the source code. So they will believe the feature tells them one thing but it won't be always correct.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by solegalli** [comment]
Hi @dodoarg 

I linked the notebook. We are good to merge this PR. 

The only thing remaining would be to remove that feature that is polemic :)

Would you be able to pick that up?

**Pull request merged**
